# Sleep Data Analysis of Mammals

Original dataset: [Kaggle Link](https://www.kaggle.com/datasets/mathurinache/sleep-dataset)

Data from StatLib (ftp stat.cmu.edu/datasets)

Data from which conclusions were drawn in the article "Sleep in Mammals: Ecological and Constitutional Correlates" by Allison, T. and Cicchetti, D. (1976), Science, November 12, vol. 194, pp. 732-734. Includes brain and body weight, life span, gestation time, time sleeping, and predation and danger indices for 62 mammals.

---

Original description
- species of animal
- body weight in kg
- brain weight in g
- slow wave ("nondreaming") sleep (hrs/day)
- paradoxical ("dreaming") sleep (hrs/day)
- total sleep (hrs/day) (sum of slow wave and paradoxical sleep)
- maximum life span (years)
- gestation time [length of pregnancy] (days)
- predation index [how likely an organism is to be preyed upon] (1-5) 1 = minimum (least likely to be preyed upon) 5 = maximum (most likely to be preyed upon)
- sleep exposure index (1-5) 1 = least exposed (e.g. animal sleeps in a well-protected den) 5 = most exposed
- overall danger index (1-5) (based on the above two indices and other information) 1 = least danger (from other animals) 5 = most danger (from other animals)

Note: Missing values denoted by -999.0

---

## 1. Step: Play around with data file and inspect columns

The idea here is to get a feeling for (i) what columns there are, (ii) what datatypes they have, and (iii) which could be useful later on

In [ ]:
import pandas as pd

# load file and save to dataframe
df = pd.read_csv("dataset.xls")

In [16]:
# inspect columns + datatypes of columns
# df.columns
df.dtypes

body_weight             float64
brain_weight            float64
max_life_span            object
gestation_time           object
predation_index           int64
sleep_exposure_index      int64
danger_index              int64
total_sleep              object
dtype: object

In [22]:
# show quick statistics
df.describe()

,body_weight,brain_weight,predation_index,sleep_exposure_index,danger_index
count,62.000000,62.000000,62.000000,62.000000,62.000000
mean,198.789984,283.134194,2.870968,2.419355,2.612903
std,899.158011,930.278942,1.476414,1.604792,1.441252
min,0.005000,0.140000,1.000000,1.000000,1.000000
25%,0.600000,4.250000,2.000000,1.000000,1.000000
50%,3.342500,17.250000,3.000000,2.000000,2.000000
75%,48.202500,166.000000,4.000000,4.000000,4.000000
max,6654.000000,5712.000000,5.000000,5.000000,5.000000

In [24]:
# looking at some entries
df.head()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9

# 2. Step: Look for missing data

Usually this would be NaN or missing data, in this case they specified them to be -999.0

In [25]:
# TODO: inspect missing data and think about how to deal with them

# 3. Step: Perform Analyses

In [26]:
# look at correlation matrix, this tells us what features are descriptive of what other features
# TODO

In [43]:
# Idea/Exercise 1: a tiger only knows some X features of the dataset table and wants to predict some Y feature. For example a tiger only knows all features except how exposed an animal is during it's sleep and wants to estimate that such that it can find the animal sleeping during the night. However, since all animals start sleeping at the same time, the tiger can only focus on animals that do not wake up earlier than the tiger. The tiger sleeps about 5 hours
# TODO